# Site Settings
title: 
email: tobiasmorville@gmail.com
description: >
  Hello, my name is Tobias and I do neuroscience.
baseurl: 
url: "https://tmorville.github.io/"
twitter_username: 
github_username:  tmorville
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM