# Site wide configuration

title: "Tobias Morville"
description: "Hello, world"
logo: # 120x120 px default image used for Twitter summary card
teaser: bio-photo.jpg
locale: en
url: https://tmorville.github.io/
feed:
path: atom.xml
categories: "Test"

# Jekyll configuration

sass:
sass_dir: _sass
style: compressed
permalink: /:categories/:title/:about
kramdown:
toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner: "Tobias Morville"
name: "Tobias"
email: "tobiasmorville@gmail.com"
twitter:
google:
ad-client:
ad-slot:
bio:
avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
